"""Generates a combined CR5+PGC-140 URDF by splicing the vendored PGC-140
gripper URDF onto the CR5 arm's Link6 via one new fixed joint.

cuRobo/Isaac Sim need a single urdf_path describing the whole arm+gripper
kinematic chain (see configs/curobo/cr5.yml's ee_link, and the single
SingleArticulation-per-prim_path assumption throughout
scripts/build_scene.py's run_teleop_loop()) -- this mirrors how cuRobo's
own bundled franka.yml already includes the Franka's hand+fingers in the
same URDF as its arm, rather than importing two separately-rooted
articulations and welding them together in USD afterward.

Both robots/cr5/urdf/cr5_robot.urdf and robots/pgc140/urdf/pgc140_robot.urdf
are left untouched -- this script only reads them and writes a new,
clearly-labeled generated file (GENERATED_URDF_PATH below). Re-run this
script whenever either source URDF changes; do not hand-edit the generated
output directly.

merge_fixed_joints=False is passed at import time (see import_cr5.py) --
kept deliberately, so PhysX composes each body's independently-authored
mass/inertia/CoM through this new fixed joint too, rather than trusting the
URDF importer's own mass-merging math for a multi-body chain.

Run standalone (no Isaac Sim/omni dependency -- stdlib only, safe to run
outside any Isaac Sim environment):
    python3 scripts/generate_cr5_pgc140_urdf.py
"""

from __future__ import annotations

import copy
import os
import xml.etree.ElementTree as ET
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CR5_URDF_PATH = REPO_ROOT / "robots" / "cr5" / "urdf" / "cr5_robot.urdf"
PGC140_URDF_PATH = REPO_ROOT / "robots" / "pgc140" / "urdf" / "pgc140_robot.urdf"
GENERATED_URDF_PATH = REPO_ROOT / "robots" / "cr5_pgc140" / "urdf" / "combined.urdf"

ARM_MOUNT_LINK = "Link6"
GRIPPER_ROOT_LINK = "pgc140_base_link"
MOUNT_JOINT_NAME = "link6_to_gripper_joint"

# FIRST-DRAFT ESTIMATE, NOT YET VISUALLY CONFIRMED. PGC-140's own
# pgc140_base_link origin (from its vendored URDF/mesh) is assumed to sit
# at its mounting-face center, matching the common industrial-gripper
# convention -- so identity is the starting guess for "flush against
# Link6's own tool-flange origin," the same way Link6 itself is a plain
# terminal link with no separate mount-frame convention (see
# robots/cr5/urdf/cr5_robot.urdf's own Link6/joint6). Dial this in the same
# practical way configs/scene/table_layout.yaml's cr5_mount.position was
# dialed in (visually, in the Isaac Sim GUI) -- this repo's own dev
# environment has no Isaac Sim/GPU available to verify it here, so treat
# this as unverified until checked live.
MOUNT_ORIGIN_XYZ = "0 0 0"
MOUNT_ORIGIN_RPY = "0 0 0"

_GENERATED_HEADER = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    # XML comments may not contain "--" ANYWHERE except as the closing
    # "-->" -- confirmed the hard way (ET.parse() raised ParseError: "not
    # well-formed (invalid token)" on an earlier draft of this comment that
    # used "--" as a clause separator, this codebase's usual prose style).
    "<!-- MACHINE-GENERATED by scripts/generate_cr5_pgc140_urdf.py.\n"
    "     Do not hand-edit. Re-run that script after changing either\n"
    "     robots/cr5/urdf/cr5_robot.urdf or\n"
    "     robots/pgc140/urdf/pgc140_robot.urdf. -->\n"
)


def _rewrite_mesh_paths(root: ET.Element, source_urdf_dir: Path, output_urdf_dir: Path) -> None:
    """Re-expresses each <mesh filename=...> (originally relative to
    source_urdf_dir, per that URDF's own convention) relative to
    output_urdf_dir instead -- the combined file lives in a third
    directory (robots/cr5_pgc140/urdf/), not either source's own urdf/
    directory, so a naive copy of the original relative string would
    resolve to the wrong place.
    """
    for mesh in root.iter("mesh"):
        old = mesh.get("filename")
        if old is None:
            continue
        absolute_mesh_path = (source_urdf_dir / old).resolve()
        mesh.set("filename", os.path.relpath(absolute_mesh_path, start=output_urdf_dir))


def generate_combined_urdf() -> Path:
    cr5_root = ET.parse(CR5_URDF_PATH).getroot()
    pgc140_root = ET.parse(PGC140_URDF_PATH).getroot()
    output_dir = GENERATED_URDF_PATH.parent

    _rewrite_mesh_paths(cr5_root, CR5_URDF_PATH.parent, output_dir)
    _rewrite_mesh_paths(pgc140_root, PGC140_URDF_PATH.parent, output_dir)

    combined_root = copy.deepcopy(cr5_root)
    combined_root.set("name", "cr5_pgc140_robot")

    for child in pgc140_root:
        combined_root.append(copy.deepcopy(child))

    mount_joint = ET.SubElement(combined_root, "joint", {"name": MOUNT_JOINT_NAME, "type": "fixed"})
    ET.SubElement(mount_joint, "origin", {"xyz": MOUNT_ORIGIN_XYZ, "rpy": MOUNT_ORIGIN_RPY})
    ET.SubElement(mount_joint, "parent", {"link": ARM_MOUNT_LINK})
    ET.SubElement(mount_joint, "child", {"link": GRIPPER_ROOT_LINK})

    ET.indent(combined_root, space="  ")
    output_dir.mkdir(parents=True, exist_ok=True)
    # xml_declaration=False: ET.tostring() with a non-"unicode" encoding
    # emits its own leading <?xml ...?> declaration by default, which would
    # otherwise duplicate the one already in _GENERATED_HEADER (two
    # declarations in one file is invalid XML) -- suppressed here so
    # _GENERATED_HEADER's is the only one.
    body = ET.tostring(combined_root, encoding="utf-8", xml_declaration=False)
    GENERATED_URDF_PATH.write_bytes(_GENERATED_HEADER.encode("utf-8") + body)
    return GENERATED_URDF_PATH


def main() -> None:
    path = generate_combined_urdf()
    print(f"[generate_cr5_pgc140_urdf] wrote {path}")


if __name__ == "__main__":
    main()
